# Generated by Django 5.1.4 on 2024-12-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pendiente', 'Pending'), ('En Progreso', 'In Progress'), ('Completada', 'Completed')], default='Pendiente', max_length=15)),
                ('priority', models.CharField(choices=[('Baja', 'Low'), ('Media', 'Medium'), ('Alta', 'High')], default='Baja', max_length=10)),
            ],
        ),
    ]
